install:
    - sudo apt-get install texlive-fonts-recommended texlive-latex-recommended texlive-math-extra texlive-latex-extra texlive-math-extra texlive-science texlive-lang-french graphviz
    - sudo apt-get install chktex

script:
    - make
    - chktex -W # Print version information.
    - chktex -q -n 6 *.tex chapters.*.tex 2>/dev/null | tee lint.out
    # If lint output is non-empty report an error.
    - test ! -s lint.out