sudo: required

install:
    - sudo apt-get install texlive-fonts-recommended
    - sudo apt-get install texlive-latex-recommended
    - sudo apt-get install texlive-math-extra
    - sudo apt-get install texlive-latex-extra
    - sudo apt-get install texlive-science
    - sudo apt-get install texlive-lang-french
    - sudo apt-get install graphviz
    - sudo apt-get install latex-xcolor
    - sudo apt-get install pgf
    - sudo apt-get install texlive-pstricks
    - sudo apt-get install texlive-pictures
    - sudo apt-get install dot2tex

script:
    - make

language: c

notifications:
  email: false